add:
	cordova plugin remove plugin-ibrdtn
	cordova plugin add ../cordova-plugin-ibrdtn

add-first:
	cordova plugin add ../cordova-plugin-ibrdtn


build:
	cordova build

clean:
	cordova clean

logcat:
	adb logcat | grep Disaster

logcat-chrome:
	adb logcat chromium:I

run:
	cordova run android
